[project]
name = "mediabin-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "duckdb>=1.3.2",
    "typer>=0.17.4",
]

[project.scripts]
mb = "mediabin.cli:app"
